project:
  type: default

execute:
  echo: true
  warning: true
  message: false
  error: false
  cache: false

format:
  revealjs:
    theme: default
    slide-number: true
    show-slide-number: all
    transition: slide
    width: 1280
    height: 720
    code-fold: false
    code-tools: true
    fig-width: 8
    fig-height: 6
    embed-resources: true  # Makes files self-contained